# Lecture 2

In [1]:
%run set_env.py
%matplotlib inline

Check versions:
  numpy version     :'1.24.3'
  matplotlib version:'3.8.2'


### Array attributes

<font color="green"><b>ndarray</b></font> is the NumPy base/super class.<br>
The ndarray class has several fields/methods.<br>
Among them:
* dtype: type of the (homogeneous) elements
* ndim : dimensionality (#axes) of the array
* shape: dimensions of the array (<font color="green"><b>tuple of ints</b></font>)
* size : #elements in the array
* itemsize: memory occupied by 1 element
* nbytes  : total #bytes consumed by the el. of the array
* strides : strides of data in memory
* flags   : <b>dictionary</b> containing info on memory use.
* T       : transpose of the ndarray

In [2]:
# arange(20) -> Linux x86_64: 'int64'
a=np.arange(20).reshape(4,5)
print(f"a := np.arange(20).reshape((4,5)) :\n{a}\n")
print(f"  type(a) :'{type(a)}'")
print(f"  a.dtype:'{a.dtype}'")
print(f"  a.ndim:'{a.ndim}'")
print(f"  a.shape:'{a.shape}'")
print(f"  a.size:'{a.size}'")
print(f"  a.itemsize:'{a.itemsize}'")
print(f"  a.nbytes:'{a.nbytes}'")
print(f"  a.strides:'{a.strides}'\n")
print(f"  a.real   :\n{a.real}\n")
print(f"  a.imag   :\n{a.imag}\n")
print(f"  a.flags:\n{a.flags}")
print(f"  a.T:\n{a.T}")

a := np.arange(20).reshape((4,5)) :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

  type(a) :'<class 'numpy.ndarray'>'
  a.dtype:'int64'
  a.ndim:'2'
  a.shape:'(4, 5)'
  a.size:'20'
  a.itemsize:'8'
  a.nbytes:'160'
  a.strides:'(40, 8)'

  a.real   :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

  a.imag   :
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

  a.flags:
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  a.T:
[[ 0  5 10 15]
 [ 1  6 11 16]
 [ 2  7 12 17]
 [ 3  8 13 18]
 [ 4  9 14 19]]


<b>Notice</b> the fundamental difference!

In [4]:
a = np.arange(20).reshape(4,5)
b = np.arange(20.).reshape(4,5)

print(f"a := np.arange(20).reshape((4,5)) :\n{a}\n")
print(f"b :=b np.arange(20.).reshape((4,5)) :\n{b}\n")
print(f"  type(a) :'{type(a)}'")
print(f"  type(b) :'{type(b)}'")

a := np.arange(20).reshape((4,5)) :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

b :=b np.arange(20.).reshape((4,5)) :
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]

  type(a) :'<class 'numpy.ndarray'>'
  type(b) :'<class 'numpy.ndarray'>'


In [5]:
print(f"  a.ndim:'{a.ndim}'")
print(f"  b.ndim:'{b.ndim}'")
print(f"  a.shape:'{a.shape}'")
print(f"  b.shape:'{b.shape}'")
print(f"  a.size:'{a.size}'")
print(f"  b.size:'{b.size}'")
print(f"  a.dtype:'{a.dtype}'")
print(f"  b.dtype:'{b.dtype}'")
print(f"  a.itemsize:'{a.itemsize}'")
print(f"  b.itemsize:'{b.itemsize}'")
print(f"  a.nbytes:'{a.nbytes}'")
print(f"  b.nbytes:'{b.nbytes}'")

  a.ndim:'2'
  b.ndim:'2'
  a.shape:'(4, 5)'
  b.shape:'(4, 5)'
  a.size:'20'
  b.size:'20'
  a.dtype:'int64'
  b.dtype:'float64'
  a.itemsize:'8'
  b.itemsize:'8'
  a.nbytes:'160'
  b.nbytes:'160'


### Create specific arrays (types & content)

#### a.Data Types

Numpy support several <font><b>native data types</b></font> e.g.:
* int8, int16, int32, int64
* uint8, uint16, uint32, uint64
* float16, float32, float64
* complex64, complex128 
* ...

In [7]:
# Create arrays of a certain data type
i1=np.arange(10,dtype=np.int32)
print(f"i1 := np.arange(10,dtype='int32'):\n  {i1}")
print(f"  i1.dtype:'{i1.dtype}'")
print(f"  i1.size :'{i1.size}'")
print(f"  i1.itemsize:'{i1.itemsize}'")
print(f"  i1.nbytes:'{i1.nbytes}'")

z1=np.arange(10,dtype='complex128')
print(f"\nz1 := np.arange(10,dtype='complex128'):\n  {z1}\n")
print(f"  z1.dtype:'{z1.dtype}'")
print(f"  z1.size :'{z1.size}'")
print(f"  z1.itemsize:'{z1.itemsize}'")
print(f"  z1.nbytes:'{z1.nbytes}'")

i1 := np.arange(10,dtype='int32'):
  [0 1 2 3 4 5 6 7 8 9]
  i1.dtype:'int32'
  i1.size :'10'
  i1.itemsize:'4'
  i1.nbytes:'40'

z1 := np.arange(10,dtype='complex128'):
  [0.+0.j 1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j 8.+0.j 9.+0.j]

  z1.dtype:'complex128'
  z1.size :'10'
  z1.itemsize:'16'
  z1.nbytes:'160'


In [8]:
# Native scalar data types in numpy:
for key in np.sctypes:
    print(f" key:{key:<8s}  value:{np.sctypes[key]}")

 key:int       value:[<class 'numpy.int8'>, <class 'numpy.int16'>, <class 'numpy.int32'>, <class 'numpy.int64'>]
 key:uint      value:[<class 'numpy.uint8'>, <class 'numpy.uint16'>, <class 'numpy.uint32'>, <class 'numpy.uint64'>]
 key:float     value:[<class 'numpy.float16'>, <class 'numpy.float32'>, <class 'numpy.float64'>, <class 'numpy.float128'>]
 key:complex   value:[<class 'numpy.complex64'>, <class 'numpy.complex128'>, <class 'numpy.complex256'>]
 key:others    value:[<class 'bool'>, <class 'object'>, <class 'bytes'>, <class 'str'>, <class 'numpy.void'>]


See also:<br>
https://docs.scipy.org/doc/numpy/user/basics.types.html

The class <font color="green"><b>np.dtype</b></font> allows one to create compound data types 
(<font color="green"><b>structured arrays</b></font> cfr. C structs).<br>
For more info:<br>
https://docs.scipy.org/doc/numpy/user/basics.rec.html

To perform a data type conversion (<font color="green"><b>cast</b></font>) between different scalar data types:
* numpy.astype(dtype) : convert array to type dtype

In [9]:
# Change dtype of an array 
f1 = np.array([1.0,2.5,3.0,7.2])
print(f"\nf1 := np.array([1.0,2.5,3.0,7.2]):\n    {f1}")
i3 = f1.astype('complex128')
print(f"  i3 := f1.astype(dtype='complex128'):\n    {i3}\n")
print(f"  i3.dtype:'{i3.dtype}'")
print(f"  i3.size :'{i3.size}'")
print(f"  i3.itemsize:'{i3.itemsize}'")
print(f"  i3.nbytes:'{i3.nbytes}'")


f1 := np.array([1.0,2.5,3.0,7.2]):
    [1.  2.5 3.  7.2]
  i3 := f1.astype(dtype='complex128'):
    [1. +0.j 2.5+0.j 3. +0.j 7.2+0.j]

  i3.dtype:'complex128'
  i3.size :'4'
  i3.itemsize:'16'
  i3.nbytes:'64'


#### b. Particular forms of ndarray

Numpy has specific <font><b>initialization</b></font> functions<br> 
A few of the most important ones:
* diag(v,k=0)                            
  + either **extracts** the diagonal (if the matrix exists)
  + or **constructs** a diagonal array. 
* empty(shape,dtype='float64',order='C') 
  + returns a new array <b>without</b> initializing its entries (i.e. mem. allocation)
* full(shape,value,dtype='float64',order='C')
  + returns a new array <b>initializing</b> its entries to <i>value</i>.
* eye(N,M=None,k=0,dtype='float64')      
  + returns a 2-D array with ones on the 'diagonal' and zeros elsewhere
* fromfunction(myfunc,shape,dtype)                          
  + returns a new array based on a function
* identity(n,dtype='float64')            
  + returns the $n$ x $n$ identity matrix
* ones(shape,dtype='float64',order='C')  
  + returns a new array completely filled with 1s 
* zeros(shape,dtype='float64',order='C') 
  + returns a new array completely filled with 0s
  

In [10]:
# Diag function
a1 = np.array([i for i in range(20)]).reshape(4,5)
print(f"  a1:\n{a1}")

# Extract the diagonal
print(f"  \n np.diag(a1):\n{np.diag(a1)}")

# Extract a SHIFTED diagonal
print(f"  \n np.diag(a1,k=1):\n{np.diag(a1,k=1)}")

# Create a diagonal matrix
print(f"  \n np.diag(range(4)):\n{np.diag(range(4))}")

# Create a SHIFTED diagonal matrix
print(f"  \n np.diag(range(4),k=1):\n{np.diag(range(4),k=1)}")

  a1:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
  
 np.diag(a1):
[ 0  6 12 18]
  
 np.diag(a1,k=1):
[ 1  7 13 19]
  
 np.diag(range(4)):
[[0 0 0 0]
 [0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]]
  
 np.diag(range(4),k=1):
[[0 0 0 0 0]
 [0 0 1 0 0]
 [0 0 0 2 0]
 [0 0 0 0 3]
 [0 0 0 0 0]]


In [11]:
# Memory allocation
a2=np.empty((2,3))
print(f"a2=np.empty((2,3)) :\n{a2}\n")

# Create ones on the diagonal
a3=np.eye(5,4,k=1,dtype='float64')
print(f"a3=np.eye(5,4,k=1,dtype='float64') :\n{a3}\n")

# Use a function (index based) to generate entries
a4=np.fromfunction(lambda x,y: x+2*y,(2,5),dtype='float64')
print(f"a4=np.fromfunction(lambda x,y: x+2*y,(2,5),dtype='float64') :\n{a4}\n")

# Return a SQUARE identity matrix
a5=np.identity(5,dtype='int64')
print(f"a5=np.identity(5,dtype='int64') :\n{a5}\n")

a6=np.ones((2,7),dtype='int64')
print(f"a6=np.ones((2,7),dtype='int64') :\n{a6}\n")

a7=np.zeros((3,4),dtype='complex128')
print(f"a7=np.zeros((3,4),dtype='complex128') :\n{a7}\n")

a8=np.full((3,5), np.pi)
print(f"a8=np.full((3,5), np.pi):\n{a8}\n")

a2=np.empty((2,3)) :
[[2.12008554e-316 0.00000000e+000 6.92077176e-310]
 [6.92077256e-310 4.13268126e-317 6.92077085e-310]]

a3=np.eye(5,4,k=1,dtype='float64') :
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

a4=np.fromfunction(lambda x,y: x+2*y,(2,5),dtype='float64') :
[[0. 2. 4. 6. 8.]
 [1. 3. 5. 7. 9.]]

a5=np.identity(5,dtype='int64') :
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

a6=np.ones((2,7),dtype='int64') :
[[1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1]]

a7=np.zeros((3,4),dtype='complex128') :
[[0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 0.+0.j]]

a8=np.full((3,5), np.pi):
[[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]]



#### c. Some other useful (random) initializations

You can also fill up your ndarray with random numbers<br>
The Numpy random generator is based on the **Mersenne Twister**.<br>
https://en.wikipedia.org/wiki/Mersenne_Twister
* numpy.random.random([size]):<br>
  Returns random floats in the half-open interval [0.0, 1.0) (i.e. Uniform Distribution)
* numpy.random.randint(low, [high=None], [size],[dtype]):<br>
  Returns random integers from low (inclusive) to high (exclusive).
* ...   

In [12]:
import numpy.random as rnd
a = rnd.random((4,5))
print(f" a:\n{a}\n")
      
b = rnd.randint(5,15,(4,6))   
print(f" b:\n{b}\n")

 a:
[[0.39001762 0.45663063 0.20326173 0.44180232 0.20640127]
 [0.06601834 0.35075481 0.741818   0.62967958 0.09667231]
 [0.73736594 0.26397453 0.98509745 0.84567954 0.03726326]
 [0.23036252 0.73954623 0.18018032 0.9473681  0.46368945]]

 b:
[[10 12 12  8  6 11]
 [11  8  6 10  9 10]
 [12 11  7 13 10  9]
 [14  7 13  7 13 10]]



### Exercise:

* Create a 5x5 matrix with the following (staggered) entries:<br>
  $ 
  \begin{equation*}
     a = 
    \begin{pmatrix}
     0 & 1 & 2 & 3 & 4 \\
     1 & 2 & 3 & 4 & 5 \\
     2 & 3 & 4 & 5 & 6 \\
     3 & 4 & 5 & 6 & 7 \\
     4 & 5 & 6 & 7 & 8
    \end{pmatrix}
    \end{equation*}
  $  
   
       (Hint: use the np.fromfunction) 
       
* Create a 6x6 'tridiagonal' matrix (see https://en.wikipedia.org/wiki/Tridiagonal_matrix)<br>
  where:
  * the 'tridiagonal' elements are True and 
  * the 'non-tridiagonal' elements are False<br>
  Boolean matrices are <font color="green"><b>key components</b></font> for fancy indexing (see later)<br>
  (<b>Hint</b>: 0:False & non-zero:True)

### Solutions:

In [ ]:
# %load ../solutions/ex2.py

### Addendum:

#### 1. np.empty_like(), np.zeros_like(), np.ones_like() functions:

Numpy allows one to create empty, zeros, ones ndarrays <br>
with the <b><font color="green">SAME</font></b> shape as an existing ndarrays.<br>
(Syntax: y = np.zeros_like(x), etc.)
  * np.empty_like()
  * np.full_like()
  * np.zeros_like()
  * np.ones_like()

In [ ]:
np.set_printoptions(precision=4)
a = np.random.random((4,6))
print(f" a:\n{a}")
b = np.zeros_like(a,dtype='int32')
print(f" b:\n{b}")

#### 2. Caveat:

In [ ]:
# To create a proper vector a Python array-type object is required
a = np.array(5)
print(f" a:{a}")
print(f" ndim:{a.ndim}")
print(f" shape:{a.shape}")
print(f" type:{type(a)}")

# should either be
b = np.array([5])
print(f"\n b:{b}")
print(f" ndim:{b.ndim}")
print(f" shape:{b.shape}")
print(f" type:{type(b)}")

# OR
c = np.atleast_1d(5)
print(f"\n c:{c}")
print(f" ndim:{c.ndim}")
print(f" shape:{c.shape}")
print(f" type:{type(c)}")