# Lecture 4

In [1]:
%run set_env.py
%matplotlib inline

Check versions:
  numpy version     :'1.24.3'
  matplotlib version:'3.7.2'


### Vector Operations & Broadcasting

* NumPy operations are done on an <b><font color="green">element-by-element</font></b> basis

In [3]:
# Regular Python: '+'/'*' 
N = 5
x = [i for i in range(N)]
y = N*[1]
print(f"  x  :{x}")
print(f"  y  :{y}")
print(f"  x+y:{x+y}")  # extend method for lists

  x  :[0, 1, 2, 3, 4]
  y  :[1, 1, 1, 1, 1]
  x+y:[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]


In [4]:
# Numpy's addition
x = np.array(x)
y = np.array(y)
print(f"  x  :\n{x}")
print(f"  y  :\n{y}")
print(f"  x+y:\n{x+y}")

  x  :
[0 1 2 3 4]
  y  :
[1 1 1 1 1]
  x+y:
[1 2 3 4 5]


<b>Note</b>:<br>
The '*' operator is overriden in NumPy as well.<br>
What is the diffference?

#### Examples:

In [5]:
# Numpy's Multiplication
x = rnd.randint(3,10,(4,4))
y = rnd.randint(1,5,(4,4))
print(f"  x:\n{x}\n")
print(f"  y:\n{y}\n")
print(f"  x*y:\n{x*y}\n")

  x:
[[6 9 3 5]
 [9 3 6 8]
 [5 9 5 7]
 [8 5 7 3]]

  y:
[[2 4 1 2]
 [2 3 2 2]
 [1 2 1 2]
 [3 1 3 3]]

  x*y:
[[12 36  3 10]
 [18  9 12 16]
 [ 5 18  5 14]
 [24  5 21  9]]



In [7]:
# b. Boolean operators working on NumPy arrays
x = rnd.randint(4,10,(12))
y = rnd.randint(4,10,(12))
print(f"  x={x}")
print(f"  y={y}\n")
print(f"  ==      : {x==y}")
print(f"  !=      : {x!=y}")
print(f"  not(!=) : {~(x!=y)}")
print(f"  >=      : {x>=y}")
print(f"  x>7     : {x>7}")

  x=[5 6 8 8 5 7 8 9 4 4 5 8]
  y=[7 6 9 7 6 9 6 6 6 9 7 5]

  ==      : [False  True False False False False False False False False False False]
  !=      : [ True False  True  True  True  True  True  True  True  True  True  True]
  not(!=) : [False  True False False False False False False False False False False]
  >=      : [False  True False  True False False  True  True False False False  True]
  x>7     : [False False  True  True False False  True  True False False False  True]


#### Combining boolean operators for ndarray objects


<font color="green"><b>Regular python</b></font> : 
* and  
* or  (inclusive or)
* not (negation operator)
* !=  (exclusive or)
 

In [ ]:
# Combining boolean operators as in REGULAR'Python' way -> ERROR
# x < 5 or y>7
# (Due to DIFFERENT syntax!)

<font color="green"><b>Numpy</b></font>:
* & : and operator
* | : inclusive or operator
* ~ : negation operator
* ^ : exclusive or (xor)

In [8]:
# Combining boolean operators in NumPy
print(f"  x                 : {x}")
print(f"  y                 : {y}\n")
v1 = (x<8) & (x>4)
print(f"  (x<8) & (x>4)     : {v1}")
v2 = (x<6) | (x>7)
print(f"  (x<6) | (x>7)     : {v2}")
v3 = ~(x==6)
print(f"  ~(x==6)           : {v3}")
v4 = (x<6) ^ (x<7)   
print(f"  (x<6) ^ (x<7)     : {v4}")

  x                 : [5 6 8 8 5 7 8 9 4 4 5 8]
  y                 : [7 6 9 7 6 9 6 6 6 9 7 5]

  (x<8) & (x>4)     : [ True  True False False  True  True False False False False  True False]
  (x<6) | (x>7)     : [ True False  True  True  True False  True  True  True  True  True  True]
  ~(x==6)           : [ True False  True  True  True  True  True  True  True  True  True  True]
  (x<6) ^ (x<7)     : [False  True False False False False False False False False False False]


### How to perform matrix multiplications in Numpy?

* Numpy operators work in an el. by el. fashion
* To perform matrix multiplications in numpy -> <font color="green"><b>np.dot</b></font> function.<br>
  But, you can also use the <font color="green"><b>@</b></font> operator.

#### Examples:

In [ ]:
# np.dot (1D case)
a = rnd.randint(4,10,(10))
b = rnd.randint(1,5,(10))

print(f"  a                 : {a}")
print(f"  b                 : {b}")
print(f"  a.b (dot-product) : {np.dot(a,b)}")
print(f"  a.b (dot.product) : {np.sum(a*b)}")

In [ ]:
# np.dot (2D case) -> Matrix Multiplication
c = rnd.randint(4,10,(2,4))
d = rnd.randint(1,5,(4,3))

print(f"  c:\n {c}\n")
print(f"  d:\n {d}\n")
print(f"  c.d (Matrix Multiplication using np.dot):\n {np.dot(c,d)}")

print(f"  c.d (Matrix Multiplication using @ operator):\n {c @ d}")

## Broadcasting

Let's start with a few simple examples/tests ...

#### Example 1:

In [ ]:
x = np.arange(1,5)
y = np.arange(10,50,10)
print(f"  x      : {x}")
print(f"  x.shape: {x.shape}\n")
print(f"  y      : {y}")
print(f"  y.shape: {y.shape}\n")
print(f"  x+y        : {x+y}")
print(f"  (x+y).shape: {(x+y).shape}")

#### Example 2:

In [9]:
x = np.arange(1,5)
y = np.arange(1,4)
print(f"  x      : {x}")
print(f"  x.shape: {x.shape}\n")
print(f"  y  : {y}".format(y))
print(f"  y.shape: {y.shape}\n")
print(f"  x+y: {x+y}")

  x      : [1 2 3 4]
  x.shape: (4,)

  y  : [1 2 3]
  y.shape: (3,)



ValueError: operands could not be broadcast together with shapes (4,) (3,) 

#### Example 3:

In [10]:
# Example 3:
x = np.arange(1,5)
y = np.random.randint(0,11,(3,4))
print(f"  x  : \n{x}")
print(f"  x.shape: {x.shape}\n")
print(f"  y  : \n{y}")
print(f"  y.shape: {y.shape}\n")
print(f"  x+y: \n{x+y}")

  x  : 
[1 2 3 4]
  x.shape: (4,)

  y  : 
[[1 8 6 9]
 [9 3 2 3]
 [9 6 7 2]]
  y.shape: (3, 4)

  x+y: 
[[ 2 10  9 13]
 [10  5  5  7]
 [10  8 10  6]]


### The rules of the (broadcasting) game

* Definition :: required to operate on (some) arrays with <b>(seemingly) mismatched</b> shapes
* Start with the trailing dimensions (i.e. from right to left)
* Two dimensions of the array are <b>compatible</b> iff
  * they both have the <b>same</b> dimension
  * <b>one</b> of the dimension is 1

Note:<br>
<font color="green"><b>Both arrays can have a different #axes</b></font>

#### Examples:

In [11]:
# Example 1
# Res: x: 4 x 1
#      y:     5
# -------------
#    x+y: 4 x 5
#---------------
x = rnd.random(4).reshape(4,1)
y = np.arange(5)
print(f"  x  : \n{x}")
print(f"  y  : \n{y}")
print(f"  x+y: \n{x+y}")

  x  : 
[[0.88063186]
 [0.65972033]
 [0.57384541]
 [0.24387396]]
  y  : 
[0 1 2 3 4]
  x+y: 
[[0.88063186 1.88063186 2.88063186 3.88063186 4.88063186]
 [0.65972033 1.65972033 2.65972033 3.65972033 4.65972033]
 [0.57384541 1.57384541 2.57384541 3.57384541 4.57384541]
 [0.24387396 1.24387396 2.24387396 3.24387396 4.24387396]]


In [ ]:
# Example 2
# Res: x: 13 x 1 x 7 x 1
#      y:      8 x 7 x 5
# -------------
#    res: 13 x 8 x 7 x 5
#---------------
x=np.arange(91).reshape((13,1,7,1))
y=np.arange(8*7*5).reshape((8,7,5))
z=x+y
print(f"  x.shape:{x.shape}")
print(f"  y.shape:{y.shape}")
print(f"  z.shape:{z.shape}")

In [12]:
# Example 3:
# Res: x: 3 x 8 x 3
#      y:     3 x 1
# -------------
#    res:     Error !! (8 & 3)
#---------------
x=np.arange(72).reshape((3,8,3))
y=np.arange(9).reshape((3,3))
z=x+y
print(f"  x.shape:{x.shape}")
print(f"  y.shape:{y.shape}")
print(f"  z.shape:{z.shape}")

ValueError: operands could not be broadcast together with shapes (3,8,3) (3,3) 

### Adding & Removing Singleton Dimensions

Axes of dim 1 (singleton dimensions) are a central tool for broadcasting.<br>
There are situations in which, one wants to:
* <b>remove</b> singleton dimensions:
  * use <b><font color="green">numpy.squeeze(a,axis=None)</font></b>
    * a: input data
    * axis : integer/tuple
    * default: all singleton dimensions
  
* <b>add</b> singleton dimensions:
  * use <b><font color="green">numpy.newaxis</font></b>
    * expand the dimension by 1 unit
    * to be added where you want to add the dimension

#### Examples:

In [13]:
# np.squeeze() function i.e. Removing Singleton axes
a=np.arange(120).reshape((2,1,3,5,1,4))
print(f"  a.shape: {a.shape}")
b=np.squeeze(a,axis=1)
print(f"  b.shape: {b.shape}")
c=np.squeeze(a,axis=4)
print(f"  c.shape: {c.shape}")
d=np.squeeze(a)
print(f"  d.shape: {d.shape}")

  a.shape: (2, 1, 3, 5, 1, 4)
  b.shape: (2, 3, 5, 1, 4)
  c.shape: (2, 1, 3, 5, 4)
  d.shape: (2, 3, 5, 4)


In [14]:
# Adding Singleton Axes
a = np.arange(24).reshape((2,3,4))
print(f"  a.shape: {a.shape}")
b = a[np.newaxis,:,:,:]
print(f"  b.shape: {b.shape}")
c = a[np.newaxis,...]
print(f"  c.shape: {c.shape}")
d=a[:,np.newaxis,:,:,np.newaxis]
print(f"  d.shape: {d.shape}")

  a.shape: (2, 3, 4)
  b.shape: (1, 2, 3, 4)
  c.shape: (1, 2, 3, 4)
  d.shape: (2, 1, 3, 4, 1)


### Exercises:

* Create the following 6x6 matrix $A$ (containing only <font color="green"><b>int32</b></font> elements)):<br>
    $\begin{equation*}A = \begin{pmatrix}
       1 & 1 &  1 &   1 &   1 &   1 \\
       1 & 8 &  1 &   1 &   1 &   1 \\ 
       1 & 1 &  27 &   1 &   1 &   1 \\
       1 & 1 &  1 &   64 &   1 &   1 \\
       1 & 1 &  1 &   1 &  125 &   1 \\
       1 & 1 &  1 &   1 &   1 &   216 
      \end{pmatrix}\end{equation*}$
* Create a new matrix $B$ ($MxN$) where:
  * $\begin{equation*}B_{ij} =  \frac{1}{X_i - Y_j} \end{equation*}$
  * $X_i$ $\in$ $X$  ($i=0,\ldots,M-1$)<br>
    is a random vector of length $M=9$ 
  * $Y_j$ $\in$ $Y$  ($j=0,\ldots,N-1$)<br>
    is a random vector of length $N=6$ 
    
  Matrices of the type $B$ are known as <font color="blue"><b>Cauchy</b></font> matrices 
  

### Solutions:

In [ ]:
# %load ../solutions/ex4.py