# Lecture 5

In [1]:
%run set_env.py
%matplotlib inline

Check versions:
  numpy version     :'1.24.3'
  matplotlib version:'3.8.2'


### Universal Functions (UFuncs)

A <font color="green"><b>universal function (ufunc)</b></font> is:
* a function which operates on an ndarray object in an <font color="green"><b>element-by-element</b></font> fashion
* an instance of the numpy.ufunc class
* a function of which many are implemented in compiled C code
* to which broadcasting rules are applied. 

The concept is similar to the <a href="https://docs.python.org/3/library/functions.html#map">map function</a> in standard Python.

#### Some ufuncs within NumPy: 

* Math operations:
  * add(x1,x2)   (called when invoked a+b)
  * power(x1,x2) (same as '**')
  * mod(x1,x2)
  * exp(x)
  * sqrt(x)
  * log(x)  (Napierian/natural logarithm)
  * ...
* Trig operations:
  * sin(x)
  * sinh(x)
  * arcsinh(x)
  * deg2rad(x)
  * rad2deg(x)
  * ..
* Bit-twiddling operations:
  * bitwise_and(x1,x2)
  * ...
* Comparison functions:
  * greater(x1,x2) (called when x1>x2 is invoked)
  * not_equal(x1,x2) (called when x1!=x2 is invoked)
  * maximum(x1,x2)  (el.-wise max.)
  * isfinite(x)   (el. test for finiteness i.e. neither Infinity nor Not a Number)
  * isinf(x)
  * isnan(x)
  * ...
  
To see all the available ufuncs, see:<br>  
https://docs.scipy.org/doc/numpy-1.13.0/reference/ufuncs.html#available-ufuncs

<font color="blue"><b>Note:</b></font>
* One can write its own UFunc -> C-API

#### Examples/Applications of UFuncs:

In [2]:
# Example 1: no BC
np.set_printoptions(precision=5)
import numpy as np
x = np.random.random((2,3,7))
y = np.exp(x)
print(f" x:\n{x}\n")
print(f" y:\n{y}\n")
import math
z=0.5
print(np.exp(z))

 x:
[[[0.83822 0.77815 0.33044 0.67148 0.51438 0.46861 0.65995]
  [0.78061 0.25108 0.30874 0.32902 0.59051 0.90688 0.04261]
  [0.76177 0.42547 0.71191 0.94619 0.35547 0.87881 0.85407]]

 [[0.42446 0.02377 0.85226 0.08439 0.64285 0.70802 0.55784]
  [0.82685 0.85018 0.39811 0.30106 0.34075 0.04122 0.32926]
  [0.65955 0.115   0.04092 0.59359 0.68107 0.53024 0.3034 ]]]

 y:
[[[2.31224 2.17744 1.39158 1.95712 1.6726  1.59777 1.9347 ]
  [2.1828  1.28541 1.36171 1.38961 1.80491 2.47659 1.04353]
  [2.14206 1.53031 2.03788 2.57588 1.42684 2.40803 2.34919]]

 [[1.52876 1.02406 2.34493 1.08805 1.90189 2.02998 1.7469 ]
  [2.28611 2.34006 1.48901 1.3513  1.40601 1.04208 1.38994]
  [1.93392 1.12187 1.04177 1.81047 1.976   1.69935 1.35445]]]

1.6487212707001282


In [3]:
# Example 2: with BC
x=np.arange(90,103,dtype=int)
y=np.arange(2,7,dtype=int).reshape((5,1))
print(f"  x:{x.shape}\n{x}\n")
print(f"  y:{y.shape}\n{y}\n")
z=np.mod(x,y)
print(f"  z:{z.shape}\n{z}\n")

  x:(13,)
[ 90  91  92  93  94  95  96  97  98  99 100 101 102]

  y:(5, 1)
[[2]
 [3]
 [4]
 [5]
 [6]]

  z:(5, 13)
[[0 1 0 1 0 1 0 1 0 1 0 1 0]
 [0 1 2 0 1 2 0 1 2 0 1 2 0]
 [2 3 0 1 2 3 0 1 2 3 0 1 2]
 [0 1 2 3 4 0 1 2 3 4 0 1 2]
 [0 1 2 3 4 5 0 1 2 3 4 5 0]]



### Reductions on ndarrays

* Besides Numpy functions which operate on ndarrays <font color="green"><b>element-wise</b></font> (UFuncs, vide supra),<br>
  there are also Numpy functions which perform <font color="green"><b>reductions</b></font> on ndarrays. 

* By <font color="green"><b>default</b></font>, the reductions operate on the <font color="green"><b>whole</b></font> ndarray.
  
* However, we can specify a particular <font color="green"><b>axis/dimension</b></font> on which to perform the reduction.  

* The functions all have a similar syntax:<br>
  numpy.func_name(a,[axis=None],[dtype=None],[out=None])<br>
  The function <font color="green"><b>func_name</b></font> can be called in 2 different ways:
  * a.func_name()    # <font color="blue"><b>Object-Oriented way</b></font> i.e. method associated to an object
  * np.func_name(a)  # <font color="blue"><b>Procedural way</b></font> i.e. array is an argument of the function

#### Mathematical Operations:
* numpy.sum(), numpy.cumsum()    : sum vs. cumulative sum
* numpy.prod(), numpy.cumprod()  : prod vs. cumulative product
* numpy.min(), numpy.max()       : min, max of a vector
* numpy.argmin(), numpy.argmax() : return indices of the min./max. values

#### Statistical Operations:
* numpy.mean, numpy.median : average, median
* numpy.std, numpy.var     : standard deviation, variance

#### Logical Operations:
* numpy.any(): Test whether ANY el. along a given axis evaluates to True
* numpy.all(): Test whether ALL el. along a given axis evaluate to True

#### Examples

###### Example 1:

In [4]:
# Example 1: 
# Invoke sum over the complete ndarray
a = np.arange(1,25).reshape((2,3,4))
print(f"  a:\n{a}\n")
print(f"  a.shape:{a.shape}\n")
print(f"  a.sum() (Object-oriented syntax): {a.sum()}\n")
print(f"  np.sum(a) (Procedural syntax)   : {np.sum(a)}\n")

  a:
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]

  a.shape:(2, 3, 4)

  a.sum() (Object-oriented syntax): 300

  np.sum(a) (Procedural syntax)   : 300



In [5]:
# Invoke sums over certain axes
a = np.arange(1,25).reshape((2,3,4))
red0 = a.sum(axis=0)
print(f"   a.sum(axis=0)   shape:{red0.shape}:\n{red0}\n")
red1 = a.sum(axis=1)
print(f"   a.sum(axis=1)   shape:{red1.shape}:\n{red1}\n")
red2 = a.sum(axis=2)
print(f"   a.sum(axis=2)   shape:{red2.shape}:\n{red2}\n")

   a.sum(axis=0)   shape:(3, 4):
[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]

   a.sum(axis=1)   shape:(2, 4):
[[15 18 21 24]
 [51 54 57 60]]

   a.sum(axis=2)   shape:(2, 3):
[[10 26 42]
 [58 74 90]]



###### Example 2:

In [7]:
np.set_printoptions(precision=4)
b = rnd.random((3,7))
print(f"  b:\n{b}\n")
print(f"  b.shape:{b.shape}\n")

av = b.mean(axis=0)
print(f"  b.mean(axis=0):\n{av}\n")

bool_matrix = b < 0.05
print(f"  bool_matrix:\n{bool_matrix}\n")
print(f"  Are they any values < 0.01? {bool_matrix.any()}")

  b:
[[0.6949 0.4331 0.134  0.1248 0.3234 0.0393 0.7781]
 [0.4048 0.7301 0.9114 0.2436 0.8402 0.4852 0.2754]
 [0.4949 0.6305 0.5781 0.2989 0.4363 0.3155 0.9806]]

  b.shape:(3, 7)

  b.mean(axis=0):
[0.5315 0.5979 0.5412 0.2224 0.5333 0.28   0.6781]

  bool_matrix:
[[False False False False False  True False]
 [False False False False False False False]
 [False False False False False False False]]

  Are they any values < 0.01? True


### Exercises:

* Generate the following vector [ 1, 3, 9, 27, ... , 729] using a UFunc.
 
* Generate a 5x10 array A with random numbers $x$ $\in$ $[0,1[$.
  * What is the maximum value for all $x$ in A?
  * What is the minimum value in each column?
  * What is the minimum value in the fourth row?
  * Are there any random numbers $x<\alpha$ or $x>\beta$?<br>You can set $\alpha:=0.02$ and $\beta:=0.98$
  
* Write the function *calc_sn(n)* (<font color="red">**without the use of for loops!**</font>): 
  * The function *calc_sn(n)* returns an array of partial sums $S_n$ ($n>0$) given by:<br>
    $\begin{equation*}
      S_n := \sum_{k=1}^{k=n} \frac{sin(k)}{k^2} 
      \end{equation*}
    $ 
  * Generate the plot $S_n$ where $n$ $\in$ $\{1,\ldots,100\}$ to visualize the absolute convergency of the series.<br>
    You can use the following code to create the matplotlib plot:<br>
      * N = 100 <br>
      * import matplotlib.pyplot as plt  <br>
      * plt.plot(np.arange(1,N+1), calc_sn(N))  <br>
      * plt.title(r"\\$ S_n = \sum_{k=1}^n \frac{sin(k)}{k^2} \\$") <br>
      * plt.xlabel(r"\\$n\\$")  <br>
      * plt.ylabel(r"\\$S_n\\$",rotation=0) <br>
      * plt.show()  <br>
    
    
  

### Solutions:

In [ ]:
# %load ../solutions/ex5.py